### ISSUE TITLE
Visual separation between tribe token in wallet and steem token in wallet

### ISSUE THREAD

**Issue by eonwarped** [hive-engine/nitrous#131]

**Comment by eonwarped** [comment]
Suggested: additional separation for the two tables

**Comment by codingdefined** [comment]
@eonwarped How do you want it to be separated, a visual guide?

**Comment by eonwarped** [comment]
I believe just a bit of spacing, different subsection, for example. Restart the table striping. Just to make it clearer that it's not part of the tribe token
