### ISSUE TITLE
Titles are garbled in some cases (Unicode text)

### ISSUE THREAD

**Issue by eonwarped** [hive-engine/nitrous#63]
Some oddity with how it's being stored in Scot. Needs investigation.

Example:
http://scot-api.steem-engine.com/@bluengel/5gbjmc

**Comment by economicstudio** [comment]
i was also curious about this.

add change from condenser for the title handling?

**Comment by eonwarped** [comment]
I will probably do that yes though would prefer the fix in the Scot API to resolve because it also is powering the feed data (titles and short description snippet), where I don't need to call to Steem API.

In case where I pull both I can prefer the steem title though.

**Comment by eonwarped** [comment]
Partially resolved in  https://github.com/steem-engine-exchange/nitrous/commit/e4edae775e885224a82c6b32946c96feb4e7f911   leaving open for full API fix.

(Reason for difference in some cases is that the fallback mechanism for fetching the content was behaving differently)
